config/routes.rb
Rails.application.routes.draw do
  resources :pago_seguridad_socials
  resources :ahorro_seguridad_socials
  resources :ivas
  resources :capitalizacions
  resources :accions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "capitalizacions#index"

  namespace :authentication, path: '', as: '' do
    resources :users, only: [:create, :new]
    resources :sessions, only: [:new, :create, :destroy]
  end
end

app/models/pago_seguridad_social.rb
class PagoSeguridadSocial < ApplicationRecord
  belongs_to :user
  belongs_to :persona
end

app/controllers/pago_seguridad_socials_controller.rb
class PagoSeguridadSocialsController < ApplicationController
  before_action :set_pago_seguridad_social, only: %i[ show edit update destroy ]

  # GET /pago_seguridad_socials or /pago_seguridad_socials.json
  def index
    @pago_seguridad_socials = PagoSeguridadSocial.all
  end

  # GET /pago_seguridad_socials/1 or /pago_seguridad_socials/1.json
  def show
  end

  # GET /pago_seguridad_socials/new
  def new
    @pago_seguridad_social = PagoSeguridadSocial.new
  end

  # GET /pago_seguridad_socials/1/edit
  def edit
  end

  # POST /pago_seguridad_socials or /pago_seguridad_socials.json
  def create
    @pago_seguridad_social = PagoSeguridadSocial.new(pago_seguridad_social_params)
    @pago_seguridad_socials.user_id =  Current.user.id
    respond_to do |format|
      if @pago_seguridad_social.save
        format.html { redirect_to pago_seguridad_social_url(@pago_seguridad_social), notice: "Pago seguridad social was successfully created." }
        format.json { render :show, status: :created, location: @pago_seguridad_social }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pago_seguridad_social.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pago_seguridad_socials/1 or /pago_seguridad_socials/1.json
  def update
    respond_to do |format|
      if @pago_seguridad_social.update(pago_seguridad_social_params)
        format.html { redirect_to pago_seguridad_social_url(@pago_seguridad_social), notice: "Pago seguridad social was successfully updated." }
        format.json { render :show, status: :ok, location: @pago_seguridad_social }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pago_seguridad_social.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pago_seguridad_socials/1 or /pago_seguridad_socials/1.json
  def destroy
    @pago_seguridad_social.destroy

    respond_to do |format|
      format.html { redirect_to pago_seguridad_socials_url, notice: "Pago seguridad social was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pago_seguridad_social
      @pago_seguridad_social = PagoSeguridadSocial.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pago_seguridad_social_params
      params.require(:pago_seguridad_social).permit(:valor, :comentario, :user_id, :persona_id)
    end
end

app/helpers/pago_seguridad_socials_helper.rb
module PagoSeguridadSocialsHelper
end

app/views/pago_seguridad_socials/_form.html.erb
<%= simple_form_for(@pago_seguridad_social) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :valor %>
    <%= f.input :comentario %>
    <%= f.input :persona, as: :select, User.all.map { |u| [u.name, u.id]} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pago_seguridad_socials/_pago_seguridad_social.html.erb
<div id="<%= dom_id pago_seguridad_social %>">
  <p>
    <strong>Valor:</strong>
    <%= pago_seguridad_social.valor %>
  </p>

  <p>
    <strong>Comentario:</strong>
    <%= pago_seguridad_social.comentario %>
  </p>

  <p>
    <strong>User:</strong>
    <%= pago_seguridad_social.user_id %>
  </p>

  <p>
    <strong>Persona:</strong>
    <%= pago_seguridad_social.persona_id %>
  </p>

</div>

app/views/pago_seguridad_socials/edit.html.erb
<h1>Editing pago seguridad social</h1>

<%= render "form", pago_seguridad_social: @pago_seguridad_social %>

<br>

<div>
  <%= link_to "Show this pago seguridad social", @pago_seguridad_social %> |
  <%= link_to "Back to pago seguridad socials", pago_seguridad_socials_path %>
</div>

app/views/pago_seguridad_socials/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pago seguridad socials</h1>

<div id="pago_seguridad_socials">
  <% @pago_seguridad_socials.each do |pago_seguridad_social| %>
    <%= render pago_seguridad_social %>
    <p>
      <%= link_to "Show this pago seguridad social", pago_seguridad_social %>
    </p>
  <% end %>
</div>

<%= link_to "New pago seguridad social", new_pago_seguridad_social_path %>

app/views/pago_seguridad_socials/new.html.erb
<h1>New pago seguridad social</h1>

<%= render "form", pago_seguridad_social: @pago_seguridad_social %>

<br>

<div>
  <%= link_to "Back to pago seguridad socials", pago_seguridad_socials_path %>
</div>

app/views/pago_seguridad_socials/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pago_seguridad_social %>

<div>
  <%= link_to "Edit this pago seguridad social", edit_pago_seguridad_social_path(@pago_seguridad_social) %> |
  <%= link_to "Back to pago seguridad socials", pago_seguridad_socials_path %>

  <%= button_to "Destroy this pago seguridad social", @pago_seguridad_social, method: :delete %>
</div>