config/routes.rb
Rails.application.routes.draw do
  resources :pago_seguridad_socials
  resources :ahorro_seguridad_socials
  resources :ivas
  resources :capitalizacions
  resources :accions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "capitalizacions#index"

  namespace :authentication, path: '', as: '' do
    resources :users, only: [:create, :new]
    resources :sessions, only: [:new, :create, :destroy]
  end
end

app/models/capitalizacion.rb
class Capitalizacion < ApplicationRecord
  belongs_to :accion
  belongs_to :user
end

app/controllers/capitalizacions_controller.rb
class CapitalizacionsController < ApplicationController
  before_action :set_capitalizacion, only: %i[ show edit update destroy ]

  # GET /capitalizacions or /capitalizacions.json
  def index
    @capitalizacions = Capitalizacion.all
    @suma = 0
    @capitalizacions.map { |x| 
      if x.accion.id == 1 || x.accion.id == 3 
        @suma += x.cantidad
      else
        @suma -= x.cantidad
      end
      
    }
    

  end

  # GET /capitalizacions/1 or /capitalizacions/1.json
  def show
  end

  # GET /capitalizacions/new
  def new
    @capitalizacion = Capitalizacion.new
  end

  # GET /capitalizacions/1/edit
  def edit
  end

  # POST /capitalizacions or /capitalizacions.json
  def create
    @capitalizacion = Capitalizacion.new(capitalizacion_params)
    @capitalizacion.user_id = Current.user.id
    respond_to do |format|
      if @capitalizacion.save
        format.html { redirect_to capitalizacion_url(@capitalizacion), notice: "Capitalizacion was successfully created." }
        format.json { render :show, status: :created, location: @capitalizacion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @capitalizacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /capitalizacions/1 or /capitalizacions/1.json
  def update
    respond_to do |format|
      if @capitalizacion.update(capitalizacion_params)
        format.html { redirect_to capitalizacion_url(@capitalizacion), notice: "Capitalizacion was successfully updated." }
        format.json { render :show, status: :ok, location: @capitalizacion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @capitalizacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /capitalizacions/1 or /capitalizacions/1.json
  def destroy
    @capitalizacion.destroy

    respond_to do |format|
      format.html { redirect_to capitalizacions_url, notice: "Capitalizacion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_capitalizacion
      @capitalizacion = Capitalizacion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def capitalizacion_params
      params.require(:capitalizacion).permit(:cantidad, :comentario, :accion_id)
    end
end

app/helpers/capitalizacions_helper.rb
module CapitalizacionsHelper
end

app/views/capitalizacions/_capitalizacion.html.erb
<tr class=" <%= capitalizacion.accion.tipo_accion == "Egreso" ?  "table-danger": "" %> ">
  <th scope="row"> <%= capitalizacion.id%> </th>
  <td> <%= capitalizacion.cantidad%> </td>
  <td> <%= capitalizacion.comentario%> </td>
  <td> <%= capitalizacion.accion.tipo_accion%> </td>
  <td> <%= capitalizacion.user.nombre%> </td>
  <td> <%= link_to "Ver", capitalizacion %></td>


</tr>

app/views/capitalizacions/_form.html.erb
    <%= simple_form_for(@capitalizacion) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs">
        <%= f.input :cantidad %>
        <%= f.input :comentario %>
        <%= f.input :accion_id, as: :select, collection: Accion.all.map{|u| [u.tipo_accion, u.id]} %>
      </div>
      
      <div class="form-actions">
        <%= f.button :submit %>
      </div>
      <% end %>

app/views/capitalizacions/edit.html.erb
<h1>Editing capitalizacion</h1>

<%= render "form", capitalizacion: @capitalizacion %>

<br>

<div>
  <%= link_to "Show this capitalizacion", @capitalizacion %> |
  <%= link_to "Back to capitalizacions", capitalizacions_path %>
</div>

app/views/capitalizacions/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">

<div class="row">
  <div id="col-8">
  <h1>Capitalizacions</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Cantidad</th>
        <th scope="col">Comentario</th>
        <th scope="col">Tipo</th>
        <th scope="col">Registrado Por</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
    
    <% @capitalizacions.each do |capitalizacion| %>

      <%= render capitalizacion %>
      
    <% end %>
    
    </tbody>
  </table>
  </div>
</div>
    <h3> ahorrado: </h3>
     <p><%= number_with_delimiter(@suma, :delimiter => ".")  %></p>
</div>
<%= link_to "New capitalizacion", new_capitalizacion_path %>

app/views/capitalizacions/new.html.erb
<h1>Nuevo registro para capitalizacion</h1>

<%= render "form", capitalizacion: @capitalizacion %>

<br>

<div>
  <%= link_to "Back to capitalizacions", capitalizacions_path %>
</div>

app/views/capitalizacions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @capitalizacion %>

<div>
  <%= link_to "Edit this capitalizacion", edit_capitalizacion_path(@capitalizacion) %> |
  <%= link_to "Back to capitalizacions", capitalizacions_path %>

  <%= button_to "Destroy this capitalizacion", @capitalizacion, method: :delete %>
</div>