config/routes.rb
Rails.application.routes.draw do
  resources :pago_seguridad_socials
  resources :ahorro_seguridad_socials
  resources :ivas
  resources :capitalizacions
  resources :accions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "capitalizacions#index"

  namespace :authentication, path: '', as: '' do
    resources :users, only: [:create, :new]
    resources :sessions, only: [:new, :create, :destroy]
  end
end

app/models/accion.rb
class Accion < ApplicationRecord
  has_many :capitalizacions
  has_many :ivas
  has_many :ahorro_seguridad_socials
end

app/controllers/accions_controller.rb
class AccionsController < ApplicationController
  before_action :set_accion, only: %i[ show edit update destroy ]

  # GET /accions or /accions.json
  def index
    @accions = Accion.all
  end

  # GET /accions/1 or /accions/1.json
  def show
  end

  # GET /accions/new
  def new
    @accion = Accion.new
  end

  # GET /accions/1/edit
  def edit
  end

  # POST /accions or /accions.json
  def create
    @accion = Accion.new(accion_params)

    respond_to do |format|
      if @accion.save
        format.html { redirect_to accion_url(@accion), notice: "Accion was successfully created." }
        format.json { render :show, status: :created, location: @accion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @accion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accions/1 or /accions/1.json
  def update
    respond_to do |format|
      if @accion.update(accion_params)
        format.html { redirect_to accion_url(@accion), notice: "Accion was successfully updated." }
        format.json { render :show, status: :ok, location: @accion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @accion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accions/1 or /accions/1.json
  def destroy
    @accion.destroy

    respond_to do |format|
      format.html { redirect_to accions_url, notice: "Accion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accion
      @accion = Accion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def accion_params
      params.require(:accion).permit(:tipo_accion)
    end
end

app/helpers/accions_helper.rb
module AccionsHelper
end

app/views/accions/_accion.html.erb
<div id="<%= dom_id accion %>">
  <p>
    <strong>Tipo accion:</strong>
    <%= accion.tipo_accion %>
  </p>

</div>

app/views/accions/_form.html.erb
<%= simple_form_for(@accion) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :tipo_accion %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/accions/edit.html.erb
<h1>Editing accion</h1>

<%= render "form", accion: @accion %>

<br>

<div>
  <%= link_to "Show this accion", @accion %> |
  <%= link_to "Back to accions", accions_path %>
</div>

app/views/accions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Accions</h1>

<div id="accions">
  <% @accions.each do |accion| %>
    <%= render accion %>
    <p>
      <%= link_to "Show this accion", accion %>
    </p>
  <% end %>
</div>

<%= link_to "New accion", new_accion_path %>

app/views/accions/new.html.erb
<h1>New accion</h1>

<%= render "form", accion: @accion %>

<br>

<div>
  <%= link_to "Back to accions", accions_path %>
</div>

app/views/accions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @accion %>

<div>
  <%= link_to "Edit this accion", edit_accion_path(@accion) %> |
  <%= link_to "Back to accions", accions_path %>

  <%= button_to "Destroy this accion", @accion, method: :delete %>
</div>