config/routes.rb
Rails.application.routes.draw do
  resources :pago_seguridad_socials
  resources :ahorro_seguridad_socials
  resources :ivas
  resources :capitalizacions
  resources :accions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "capitalizacions#index"

  namespace :authentication, path: '', as: '' do
    resources :users, only: [:create, :new]
    resources :sessions, only: [:new, :create, :destroy]
  end
end

app/views/header/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Bombas y Tanques Dashboard</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= capitalizacions_path%>">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Movimientos
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="<%= capitalizacions_path%>">Capitalizacion</a></li>
            <li><a class="dropdown-item" href="<%= ivas_path%>">IVA</a></li>
            
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="<%= ahorro_seguridad_socials_path%>">Ahorro Seguridad</a></li>
          </ul>
        </li>
        <div class="ms-auto">
          <div class="ms-auto p-2"><a href="" ><%= link_to "cerrar sesión", session_path(Current.user.id),data: {turbo_method: :delete} if Current.user %></a></div>
        </div>
      </ul>
      